package impl

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/kubeagi/arcadia/graphql-server/go-server/graph/generated"
	"github.com/kubeagi/arcadia/graphql-server/go-server/pkg/auth"
	"github.com/kubeagi/arcadia/graphql-server/go-server/pkg/client"
	md "github.com/kubeagi/arcadia/graphql-server/go-server/pkg/model"
)

// CreateModel is the resolver for the createModel field.
func (r *modelMutationResolver) CreateModel(ctx context.Context, obj *generated.ModelMutation, input generated.CreateModelInput) (*generated.Model, error) {
	token := auth.ForOIDCToken(ctx)
	c, err := client.GetClient(token)
	if err != nil {
		return nil, err
	}

	return md.CreateModel(ctx, c, input)
}

// UpdateModel is the resolver for the updateModel field.
func (r *modelMutationResolver) UpdateModel(ctx context.Context, obj *generated.ModelMutation, input *generated.UpdateModelInput) (*generated.Model, error) {
	token := auth.ForOIDCToken(ctx)
	c, err := client.GetClient(token)
	if err != nil {
		return nil, err
	}

	return md.UpdateModel(ctx, c, input)
}

// DeleteModel is the resolver for the deleteModel field.
func (r *modelMutationResolver) DeleteModel(ctx context.Context, obj *generated.ModelMutation, input *generated.DeleteModelInput) (*string, error) {
	token := auth.ForOIDCToken(ctx)
	c, err := client.GetClient(token)
	if err != nil {
		return nil, err
	}
	name := ""
	labelSelector, fieldSelector := "", ""
	if input.Name != nil {
		name = *input.Name
	}
	if input.FieldSelector != nil {
		fieldSelector = *input.FieldSelector
	}
	if input.LabelSelector != nil {
		labelSelector = *input.LabelSelector
	}
	return md.DeleteModel(ctx, c, name, input.Namespace, labelSelector, fieldSelector)
}

// GetModel is the resolver for the getModel field.
func (r *modelQueryResolver) GetModel(ctx context.Context, obj *generated.ModelQuery, name string, namespace string) (*generated.Model, error) {
	token := auth.ForOIDCToken(ctx)
	c, err := client.GetClient(token)
	if err != nil {
		return nil, err
	}
	return md.ReadModel(ctx, c, name, namespace)
}

// ListModels is the resolver for the listModels field.
func (r *modelQueryResolver) ListModels(ctx context.Context, obj *generated.ModelQuery, input generated.ListCommonInput) (*generated.PaginatedResult, error) {
	token := auth.ForOIDCToken(ctx)
	c, err := client.GetClient(token)
	if err != nil {
		return nil, err
	}

	return md.ListModels(ctx, c, input)
}

// Model is the resolver for the Model field.
func (r *mutationResolver) Model(ctx context.Context) (*generated.ModelMutation, error) {
	return &generated.ModelMutation{}, nil
}

// Model is the resolver for the Model field.
func (r *queryResolver) Model(ctx context.Context) (*generated.ModelQuery, error) {
	return &generated.ModelQuery{}, nil
}

// ModelMutation returns generated.ModelMutationResolver implementation.
func (r *Resolver) ModelMutation() generated.ModelMutationResolver { return &modelMutationResolver{r} }

// ModelQuery returns generated.ModelQueryResolver implementation.
func (r *Resolver) ModelQuery() generated.ModelQueryResolver { return &modelQueryResolver{r} }

type modelMutationResolver struct{ *Resolver }
type modelQueryResolver struct{ *Resolver }
