FROM nvidia/cuda:11.7.1-runtime-ubuntu20.04

# enable python3.9 as the default agi runtime
RUN apt-get update -y && apt-get install -y python3.9 python3.9-distutils curl
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.9 get-pip.py

# install agi libraries
RUN pip3 install fschat




