//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 KubeAGI.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIChain) DeepCopyInto(out *APIChain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIChain.
func (in *APIChain) DeepCopy() *APIChain {
	if in == nil {
		return nil
	}
	out := new(APIChain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIChain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIChainList) DeepCopyInto(out *APIChainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIChain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIChainList.
func (in *APIChainList) DeepCopy() *APIChainList {
	if in == nil {
		return nil
	}
	out := new(APIChainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIChainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIChainSpec) DeepCopyInto(out *APIChainSpec) {
	*out = *in
	out.CommonSpec = in.CommonSpec
	in.CommonChainConfig.DeepCopyInto(&out.CommonChainConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIChainSpec.
func (in *APIChainSpec) DeepCopy() *APIChainSpec {
	if in == nil {
		return nil
	}
	out := new(APIChainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIChainStatus) DeepCopyInto(out *APIChainStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIChainStatus.
func (in *APIChainStatus) DeepCopy() *APIChainStatus {
	if in == nil {
		return nil
	}
	out := new(APIChainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonChainConfig) DeepCopyInto(out *CommonChainConfig) {
	*out = *in
	out.Memory = in.Memory
	if in.StopWords != nil {
		in, out := &in.StopWords, &out.StopWords
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonChainConfig.
func (in *CommonChainConfig) DeepCopy() *CommonChainConfig {
	if in == nil {
		return nil
	}
	out := new(CommonChainConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMChain) DeepCopyInto(out *LLMChain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMChain.
func (in *LLMChain) DeepCopy() *LLMChain {
	if in == nil {
		return nil
	}
	out := new(LLMChain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMChain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMChainList) DeepCopyInto(out *LLMChainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LLMChain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMChainList.
func (in *LLMChainList) DeepCopy() *LLMChainList {
	if in == nil {
		return nil
	}
	out := new(LLMChainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LLMChainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMChainSpec) DeepCopyInto(out *LLMChainSpec) {
	*out = *in
	out.CommonSpec = in.CommonSpec
	in.CommonChainConfig.DeepCopyInto(&out.CommonChainConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMChainSpec.
func (in *LLMChainSpec) DeepCopy() *LLMChainSpec {
	if in == nil {
		return nil
	}
	out := new(LLMChainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMChainStatus) DeepCopyInto(out *LLMChainStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMChainStatus.
func (in *LLMChainStatus) DeepCopy() *LLMChainStatus {
	if in == nil {
		return nil
	}
	out := new(LLMChainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Memory) DeepCopyInto(out *Memory) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Memory.
func (in *Memory) DeepCopy() *Memory {
	if in == nil {
		return nil
	}
	out := new(Memory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetrievalQAChain) DeepCopyInto(out *RetrievalQAChain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetrievalQAChain.
func (in *RetrievalQAChain) DeepCopy() *RetrievalQAChain {
	if in == nil {
		return nil
	}
	out := new(RetrievalQAChain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RetrievalQAChain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetrievalQAChainList) DeepCopyInto(out *RetrievalQAChainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RetrievalQAChain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetrievalQAChainList.
func (in *RetrievalQAChainList) DeepCopy() *RetrievalQAChainList {
	if in == nil {
		return nil
	}
	out := new(RetrievalQAChainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RetrievalQAChainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetrievalQAChainSpec) DeepCopyInto(out *RetrievalQAChainSpec) {
	*out = *in
	out.CommonSpec = in.CommonSpec
	in.CommonChainConfig.DeepCopyInto(&out.CommonChainConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetrievalQAChainSpec.
func (in *RetrievalQAChainSpec) DeepCopy() *RetrievalQAChainSpec {
	if in == nil {
		return nil
	}
	out := new(RetrievalQAChainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetrievalQAChainStatus) DeepCopyInto(out *RetrievalQAChainStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetrievalQAChainStatus.
func (in *RetrievalQAChainStatus) DeepCopy() *RetrievalQAChainStatus {
	if in == nil {
		return nil
	}
	out := new(RetrievalQAChainStatus)
	in.DeepCopyInto(out)
	return out
}
