apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: {{ .Release.Name }}-arcadia
spec:
  selector:
    matchLabels:
      control-plane:  {{ .Release.Name }}-arcadia
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: {{ .Release.Name }}-arcadia
    spec:
      securityContext:
        runAsNonRoot: true
        # TODO(user): For common cases that do not require escalating privileges
        # it is recommended to ensure that all your Pods/Containers are restrictive.
        # More info: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        # Please uncomment the following code if your project does NOT have to work on old Kubernetes
        # versions < 1.19 or on vendors versions which do NOT support this field by default (i.e. Openshift < 4.11 ).
        # seccompProfile:
        #   type: RuntimeDefault
      containers:
      - command:
        - /manager
        - -zap-log-level={{ .Values.controller.loglevel }}
        - -v={{ .Values.controller.loglevel }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: DEFAULT_CONFIG
            value: {{ .Release.Name }}-config
        image: {{ .Values.controller.image }}
        imagePullPolicy: {{ .Values.controller.imagePullPolicy }}
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources: {{ toYaml .Values.controller.resources | nindent 10 }} 
      serviceAccountName: {{ .Release.Name }}
      terminationGracePeriodSeconds: 10
