{{- if .Values.chromadb.enabled }}
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: VectorStore
metadata:
  name:  {{ .Release.Name }}-vectorstore
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  displayName: "向量数据库"
  description: "默认系统向量数据库"
  endpoint:
    url: 'http://{{ .Release.Name }}-chromadb.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.chromadb.chromadb.serverHttpPort }}'
  chroma:
    distanceFunction: cosine
{{- end }}

{{- if .Values.postgresql.enabled }}
---
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: VectorStore
metadata:
  name:  {{ .Release.Name }}-pgvector-vectorstore
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  displayName: "pgvector 向量数据库"
  description: "pgvector 类型的向量数据库"
  pgvector:
    dataSourceRef:
      apiGroup: arcadia.kubeagi.k8s.com.cn
      kind: Datasource
      name: {{ .Release.Name }}-postgresql
      namespace: {{ .Release.Namespace }}
{{- end }}
