package impl

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"

	"github.com/kubeagi/arcadia/apiserver/graph/generated"
	"github.com/kubeagi/arcadia/apiserver/pkg/application"
)

// CreateApplication is the resolver for the createApplication field.
func (r *applicationMutationResolver) CreateApplication(ctx context.Context, obj *generated.ApplicationMutation, input generated.CreateApplicationMetadataInput) (*generated.ApplicationMetadata, error) {
	c, err := getClientFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return application.CreateApplication(ctx, c, input)
}

// UpdateApplication is the resolver for the updateApplication field.
func (r *applicationMutationResolver) UpdateApplication(ctx context.Context, obj *generated.ApplicationMutation, input generated.UpdateApplicationMetadataInput) (*generated.ApplicationMetadata, error) {
	c, err := getClientFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return application.UpdateApplication(ctx, c, input)
}

// DeleteApplication is the resolver for the deleteApplication field.
func (r *applicationMutationResolver) DeleteApplication(ctx context.Context, obj *generated.ApplicationMutation, input generated.DeleteCommonInput) (*string, error) {
	c, err := getClientFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return application.DeleteApplication(ctx, c, input)
}

// UpdateApplicationConfig is the resolver for the updateApplicationConfig field.
func (r *applicationMutationResolver) UpdateApplicationConfig(ctx context.Context, obj *generated.ApplicationMutation, input generated.UpdateApplicationConfigInput) (*generated.Application, error) {
	c, err := getClientFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return application.UpdateApplicationConfig(ctx, c, input)
}

// GetApplication is the resolver for the getApplication field.
func (r *applicationQueryResolver) GetApplication(ctx context.Context, obj *generated.ApplicationQuery, name string, namespace string) (*generated.Application, error) {
	c, err := getClientFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return application.GetApplication(ctx, c, name, namespace)
}

// ListApplicationMetadata is the resolver for the listApplicationMetadata field.
func (r *applicationQueryResolver) ListApplicationMetadata(ctx context.Context, obj *generated.ApplicationQuery, input generated.ListCommonInput) (*generated.PaginatedResult, error) {
	c, err := getClientFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return application.ListApplicationMeatadatas(ctx, c, input)
}

// Application is the resolver for the Application field.
func (r *mutationResolver) Application(ctx context.Context) (*generated.ApplicationMutation, error) {
	return &generated.ApplicationMutation{}, nil
}

// Application is the resolver for the Application field.
func (r *queryResolver) Application(ctx context.Context) (*generated.ApplicationQuery, error) {
	return &generated.ApplicationQuery{}, nil
}

// ApplicationMutation returns generated.ApplicationMutationResolver implementation.
func (r *Resolver) ApplicationMutation() generated.ApplicationMutationResolver {
	return &applicationMutationResolver{r}
}

// ApplicationQuery returns generated.ApplicationQueryResolver implementation.
func (r *Resolver) ApplicationQuery() generated.ApplicationQueryResolver {
	return &applicationQueryResolver{r}
}

type applicationMutationResolver struct{ *Resolver }
type applicationQueryResolver struct{ *Resolver }
