package impl

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"

	"github.com/kubeagi/arcadia/apiserver/graph/generated"
	"github.com/kubeagi/arcadia/apiserver/pkg/node"
)

// ListNodes is the resolver for the listNodes field.
func (r *nodeQueryResolver) ListNodes(ctx context.Context, obj *generated.NodeQuery, input *generated.ListNodeInput) (*generated.PaginatedResult, error) {
	c, err := getClientFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	return node.ListK8sNodes(ctx, c, *input)
}

// Node is the resolver for the Node field.
func (r *queryResolver) Node(ctx context.Context) (*generated.NodeQuery, error) {
	return &generated.NodeQuery{}, nil
}

// NodeQuery returns generated.NodeQueryResolver implementation.
func (r *Resolver) NodeQuery() generated.NodeQueryResolver { return &nodeQueryResolver{r} }

type nodeQueryResolver struct{ *Resolver }
