query allDataProcessListByPage($input: AllDataProcessListByPageInput!){
  dataProcess {
    allDataProcessListByPage(input: $input) {
      status
      data {
        id
        name
        status
        pre_data_set_name
        pre_data_set_version
        post_data_set_name
        post_data_set_version
        start_datetime
      }
      message
    }
  }
}

query allDataProcessListByCount($input: AllDataProcessListByCountInput!){
  dataProcess {
    allDataProcessListByCount(input: $input) {
      status
      data
      message
    }
  }
}

query dataProcessSupportType{
  dataProcess {
    dataProcessSupportType {
      status
      data {
        name
        description
        children {
          name
          zh_name
          description
          enable
        }
      }
      message
    }
  }
}

query dataProcessDetails($input: DataProcessDetailsInput){
  dataProcess {
    dataProcessDetails {
      status
      data {
        id
        status
        file_type
        pre_dataset_name
        pre_dataset_version
        post_dataset_name
        post_dataset_version
        file_num
        start_time
        end_time
        config {
          name
          description
          status
          children {
            name
            enable
            zh_name
            description
            preview {
              file_name
              content {
                pre
                post
              }
            }
          }
        }
      }
      message
    }
  }
}

mutation createDataProcessTask($input: AddDataProcessInput) {
  dataProcess {
    createDataProcessTask(input: $input) {
      status
      data
      message
    }
  }
}

mutation deleteDataProcessTask($input: DeleteDataProcessInput) {
  dataProcess {
    deleteDataProcessTask(input: $input) {
      status
      data
      message
    }
  }
}
