# create
mutation createEmbedder($input: CreateEmbedderInput!) {
  Embedder {
    createEmbedder(input: $input) {
      name
      namespace
      labels
      annotations
      displayName
      description
      type
      provider
      updateTimestamp
      status
      message
    }
  }
}

# update
mutation updateEmbedder($input: UpdateEmbedderInput) {
  Embedder {
    updateEmbedder(input: $input) {
      name
      namespace
      labels
      annotations
      displayName
      description
      provider
      type
      updateTimestamp
      status
      message
    }
  }
}

# delete
mutation deleteEmbedders($input: DeleteCommonInput!) {
  Embedder {
    deleteEmbedders(input: $input)
  }
}

# list embedders
query listEmbedders($input: ListCommonInput!) {
  Embedder {
    listEmbedders(input: $input) {
    totalCount
    hasNextPage
    nodes {
      ... on Embedder {
        name
        namespace
        labels
        annotations
        displayName
        description
        provider
        type
        updateTimestamp
        status
        message
      }
      }
    }
  }
}

# get embedder
query getEmbedder($name: String!, $namespace: String!) {
  Embedder {
    getEmbedder(name: $name, namespace: $namespace) {
        name
        namespace
        labels
        annotations
        displayName
        description
        provider
        type
        updateTimestamp
    }
  }
}
