# list
query listKnowledgeBases($input: ListKnowledgeBaseInput!){
  KnowledgeBase {
    listKnowledgeBases(input: $input) {
      totalCount
      hasNextPage
      nodes {
        ... on KnowledgeBase {
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          status
          updateTimestamp
          embedder {
            kind
            Name
          }
          vectorStore{
            kind
            Name
          }
          fileGroupDetails {
            source{
              kind
              Name
            }
            filedetails{
                path
                phase
            }
          }
        }
      }
    }
  }
}

# get
query getKnowledgeBase($name: String!, $namespace: String!) {
  KnowledgeBase {
    getKnowledgeBase(name: $name, namespace: $namespace){
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          status
          updateTimestamp
          embedder {
            kind
            Name
          }
          vectorStore{
            kind
            Name
          }
          fileGroupDetails {
            source{
              kind
              Name
            }
            filedetails{
                path
                phase
            }
          }
    }
  }
}

# create
mutation createKnowledgeBase($input: CreateKnowledgeBaseInput!) {
  KnowledgeBase {
    createKnowledgeBase(input: $input) {
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          status
          updateTimestamp
          embedder {
            kind
            Name
          }
          vectorStore{
            kind
            Name
          }
          fileGroupDetails {
            source{
              kind
              Name
            }
            filedetails{
                path
                phase
            }
          }
    }
  }
}

# update
mutation updateKnowledgeBase($input: UpdateKnowledgeBaseInput) {
  KnowledgeBase {
    updateKnowledgeBase(input: $input){
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          status
          updateTimestamp
          embedder {
            kind
            Name
          }
          vectorStore{
            kind
            Name
          }
          fileGroupDetails {
            source{
              kind
              Name
            }
            filedetails{
                path
                phase
            }
          }
    }
  }
}

# delete
mutation deleteKnowledgeBase($input: DeleteKnowledgeBaseInput) {
  KnowledgeBase {
    deleteKnowledgeBase(input: $input)
  }
}
