# list
query listModels($input: ListCommonInput!){
  Model {
    listModels(input: $input) {
      totalCount
      hasNextPage
      nodes {
        __typename
        ... on Model {
          id
          creationTimestamp
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          status
          types
          updateTimestamp
        }
      }
    }
  }
}

# get
query getModel($name: String!, $namespace: String!) {
  Model {
    getModel(name: $name, namespace: $namespace){
          id
          creationTimestamp
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          status
          types
          updateTimestamp
    }
  }
}

# create
mutation createModel($input: CreateModelInput!) {
  Model {
    createModel(input: $input) {
          id
          creationTimestamp
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          status
          types
          updateTimestamp
    }
  }
}

# update
mutation updateModel($input: UpdateModelInput) {
  Model {
    updateModel(input: $input){
          id
          creationTimestamp
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          status
          types
          updateTimestamp
    }
  }
}

# delete
mutation deleteModel($input: DeleteModelInput) {
  Model {
    deleteModel(input: $input)
  }
}
