# list
query listWorkers($input: ListWorkerInput!){
  Worker {
    listWorkers(input: $input) {
      totalCount
      hasNextPage
      nodes {
        __typename
        ... on Worker {
          id
          creationTimestamp
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          status
          updateTimestamp
          model
          modelTypes
          resources {
            cpu
            memory
            nvidiaGPU
          }
        }
      }
    }
  }
}

# get
query getWorker($name: String!, $namespace: String!) {
  Worker {
    getWorker(name: $name, namespace: $namespace){
          id
          creationTimestamp
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          status
          updateTimestamp
          model
          modelTypes
          resources {
            cpu
            memory
            nvidiaGPU
          }
    }
  }
}

# create
mutation createWorker($input: CreateWorkerInput!) {
  Worker {
    createWorker(input: $input) {
          id
          creationTimestamp
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          status
          updateTimestamp
          model
          modelTypes
          resources {
            cpu
            memory
            nvidiaGPU
          }
    }
  }
}

# update
mutation updateWorker($input: UpdateWorkerInput) {
  Worker {
    updateWorker(input: $input){
          id
          creationTimestamp
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          status
          updateTimestamp
          resources {
            cpu
            memory
            nvidiaGPU
          }
          model
          modelTypes
    }
  }
}

# delete
mutation deleteWorkers($input: DeleteCommonInput) {
  Worker {
    deleteWorkers(input: $input)
  }
}
