# permissions for end users to view llms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: llm-viewer-role
rules:
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms/status
  verbs:
  - get
