# permissions for end users to edit llms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: llm-editor-role
rules:
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - llms/status
  verbs:
  - get
