# permissions for end users to edit prompts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prompt-editor-role
rules:
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts/status
  verbs:
  - get
