# permissions for end users to view prompts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prompt-viewer-role
rules:
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - prompts/status
  verbs:
  - get
