# permissions for end users to edit vectorstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vectorstore-editor-role
rules:
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - vectorstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - vectorstores/status
  verbs:
  - get
