//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 KubeAGI.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package appnode

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChainRef) DeepCopyInto(out *ChainRef) {
	*out = *in
	out.CommonRef = in.CommonRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChainRef.
func (in *ChainRef) DeepCopy() *ChainRef {
	if in == nil {
		return nil
	}
	out := new(ChainRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonOrInPutOrOutputRef) DeepCopyInto(out *CommonOrInPutOrOutputRef) {
	*out = *in
	if in.APIGroup != nil {
		in, out := &in.APIGroup, &out.APIGroup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonOrInPutOrOutputRef.
func (in *CommonOrInPutOrOutputRef) DeepCopy() *CommonOrInPutOrOutputRef {
	if in == nil {
		return nil
	}
	out := new(CommonOrInPutOrOutputRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonRef) DeepCopyInto(out *CommonRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonRef.
func (in *CommonRef) DeepCopy() *CommonRef {
	if in == nil {
		return nil
	}
	out := new(CommonRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseRef) DeepCopyInto(out *KnowledgeBaseRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseRef.
func (in *KnowledgeBaseRef) DeepCopy() *KnowledgeBaseRef {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMChainRef) DeepCopyInto(out *LLMChainRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMChainRef.
func (in *LLMChainRef) DeepCopy() *LLMChainRef {
	if in == nil {
		return nil
	}
	out := new(LLMChainRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMRef) DeepCopyInto(out *LLMRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMRef.
func (in *LLMRef) DeepCopy() *LLMRef {
	if in == nil {
		return nil
	}
	out := new(LLMRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromptRef) DeepCopyInto(out *PromptRef) {
	*out = *in
	out.CommonRef = in.CommonRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromptRef.
func (in *PromptRef) DeepCopy() *PromptRef {
	if in == nil {
		return nil
	}
	out := new(PromptRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetrieverRef) DeepCopyInto(out *RetrieverRef) {
	*out = *in
	out.CommonRef = in.CommonRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetrieverRef.
func (in *RetrieverRef) DeepCopy() *RetrieverRef {
	if in == nil {
		return nil
	}
	out := new(RetrieverRef)
	in.DeepCopyInto(out)
	return out
}
