FROM nvidia/cuda:12.2.0-runtime-ubuntu20.04

ENV TZ=Asia/Shanghai

RUN sed -i 's/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list
RUN sed -i 's/security.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y tzdata \
    && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata

RUN apt-get update -y && apt-get install -y python3.9 python3.9-distutils curl python3-pip
RUN python3.9 -m pip install tomli -i https://pypi.mirrors.ustc.edu.cn/simple/
RUN python3.9 -m pip install setuptools_scm -i https://pypi.mirrors.ustc.edu.cn/simple/
RUN python3.9 -m pip install wavedrom -i https://pypi.mirrors.ustc.edu.cn/simple/
RUN python3.9 -m pip install fschat -i https://pypi.mirrors.ustc.edu.cn/simple/
RUN python3.9 -m pip install fschat[model_worker,webui] pydantic==1.10.13 -i https://pypi.mirrors.ustc.edu.cn/simple/

# required by vllm
# RUN python3.9 -m pip install vllm -i https://pypi.mirrors.ustc.edu.cn/simple/

# required by qwen
# might also install flash-attention to improve performance
# RUN python3.9 -m pip install transformers==4.32.0 accelerate tiktoken einops scipy transformers_stream_generator==0.0.4 -i https://pypi.mirrors.ustc.edu.cn/simple/

# required by qwen quantize
# RUN python3.9 -m pip install auto-gptq optimum -i https://pypi.mirrors.ustc.edu.cn/simple/qwn