// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateDatasourceInput struct {
	Name          string                 `json:"name"`
	Namespace     string                 `json:"namespace"`
	Labels        map[string]interface{} `json:"labels,omitempty"`
	Annotations   map[string]interface{} `json:"annotations,omitempty"`
	DisplayName   string                 `json:"displayName"`
	Description   *string                `json:"description,omitempty"`
	Endpointinput *EndpointInput         `json:"endpointinput,omitempty"`
	Ossinput      *OssInput              `json:"ossinput,omitempty"`
}

type Datasource struct {
	Name            string                 `json:"name"`
	Namespace       string                 `json:"namespace"`
	Labels          map[string]interface{} `json:"labels,omitempty"`
	Annotations     map[string]interface{} `json:"annotations,omitempty"`
	Creator         *string                `json:"creator,omitempty"`
	DisplayName     string                 `json:"displayName"`
	Endpoint        *Endpoint              `json:"endpoint,omitempty"`
	Oss             *Oss                   `json:"oss,omitempty"`
	Status          *bool                  `json:"status,omitempty"`
	FileCount       *int                   `json:"fileCount,omitempty"`
	UpdateTimestamp time.Time              `json:"updateTimestamp"`
}

type DeleteDatasourceInput struct {
	Name          *string `json:"name,omitempty"`
	Namespace     string  `json:"namespace"`
	LabelSelector *string `json:"labelSelector,omitempty"`
	FieldSelector *string `json:"fieldSelector,omitempty"`
}

type Endpoint struct {
	URL        *string               `json:"url,omitempty"`
	AuthSecret *TypedObjectReference `json:"authSecret,omitempty"`
	Insecure   *bool                 `json:"insecure,omitempty"`
}

type EndpointInput struct {
	URL        *string                    `json:"url,omitempty"`
	AuthSecret *TypedObjectReferenceInput `json:"authSecret,omitempty"`
	Insecure   *bool                      `json:"insecure,omitempty"`
}

type ListDatasourceInput struct {
	Name          *string `json:"name,omitempty"`
	Namespace     string  `json:"namespace"`
	DisplayName   *string `json:"displayName,omitempty"`
	LabelSelector *string `json:"labelSelector,omitempty"`
	FieldSelector *string `json:"fieldSelector,omitempty"`
	Page          *int    `json:"page,omitempty"`
	PageSize      *int    `json:"pageSize,omitempty"`
	Keyword       *string `json:"keyword,omitempty"`
}

type Oss struct {
	Bucket *string `json:"bucket,omitempty"`
	Object *string `json:"Object,omitempty"`
}

type OssInput struct {
	Bucket *string `json:"bucket,omitempty"`
	Object *string `json:"Object,omitempty"`
}

type PaginatedDatasource struct {
	HasNextPage bool          `json:"hasNextPage"`
	Nodes       []*Datasource `json:"nodes,omitempty"`
	Page        *int          `json:"page,omitempty"`
	PageSize    *int          `json:"pageSize,omitempty"`
	TotalCount  int           `json:"totalCount"`
}

type TypedObjectReference struct {
	APIGroup  *string `json:"apiGroup,omitempty"`
	Kind      string  `json:"kind"`
	Name      string  `json:"Name"`
	Namespace *string `json:"Namespace,omitempty"`
}

type TypedObjectReferenceInput struct {
	APIGroup  *string `json:"apiGroup,omitempty"`
	Kind      string  `json:"kind"`
	Name      string  `json:"Name"`
	Namespace *string `json:"Namespace,omitempty"`
}

type UpdateDatasourceInput struct {
	Name        string                 `json:"name"`
	Namespace   string                 `json:"namespace"`
	Labels      map[string]interface{} `json:"labels,omitempty"`
	Annotations map[string]interface{} `json:"annotations,omitempty"`
	DisplayName string                 `json:"displayName"`
	Description *string                `json:"description,omitempty"`
}
