apiVersion: v1
kind: Service
metadata:
  name: fschat-service
spec:
  type: NodePort
  selector:
    app: fschat
  ports:
    - name: {{ .Values.controllerService.name}}
      port: 21001
      targetPort: 21001
    - name: {{ .Values.apiService.name }}
      port: 8000
      targetPort: 8000