mutation createApplication($input:CreateApplicationMetadataInput!){
    Application{
        createApplication(input: $input) {
            name
            namespace
            id
            labels
            annotations
            displayName
            description
            icon
            creator
            creationTimestamp
            updateTimestamp
            isPublic
            isRecommended
            status
            category
            notReadyReasonCode
        }
    }
}

mutation updateApplication($input: UpdateApplicationMetadataInput!){
    Application{
        updateApplication(input: $input) {
            name
            namespace
            id
            labels
            annotations
            displayName
            description
            icon
            creator
            creationTimestamp
            updateTimestamp
            isPublic
            isRecommended
            status
            category
            notReadyReasonCode
        }
    }
}

mutation deleteApplication($input: DeleteCommonInput!){
    Application{
        deleteApplication(input: $input)
    }
}
mutation updateApplicationConfig($input: UpdateApplicationConfigInput!){
    Application{
        updateApplicationConfig(input: $input) {
            metadata {
                name
                namespace
                id
                labels
                annotations
                displayName
                description
                icon
                creator
                creationTimestamp
                updateTimestamp
                isPublic
                isRecommended
                status
                category
                notReadyReasonCode
            }
            prologue
            model
            llm
            temperature
            maxLength
            maxTokens
            conversionWindowSize
            knowledgebase
            knowledgebases
            scoreThreshold
            numDocuments
            docNullReturn
            userPrompt
            systemPrompt
            showRespInfo
            showRetrievalInfo
            showNextGuide
            tools {
                name
                params
            }
            enableRerank
            rerankModel
            enableMultiQuery
            chatTimeout
            enableUploadFile
            chunkSize
            chunkOverlap
            batchSize
        }
    }
}

query getApplication($name: String!, $namespace: String!){
    Application{
        getApplication(name: $name, namespace: $namespace) {
            metadata {
                name
                namespace
                id
                labels
                annotations
                displayName
                description
                icon
                creator
                creationTimestamp
                updateTimestamp
                isPublic
                isRecommended
                status
                category
                notReadyReasonCode
            }
            prologue
            model
            llm
            temperature
            maxLength
            maxTokens
            conversionWindowSize
            knowledgebase
            knowledgebases
            scoreThreshold
            numDocuments
            docNullReturn
            userPrompt
            systemPrompt
            showRespInfo
            showRetrievalInfo
            showNextGuide
            tools {
                name
                params
            }
            enableRerank
            rerankModel
            enableMultiQuery
            chatTimeout
            enableUploadFile
            chunkSize
            chunkOverlap
            batchSize
        }
    }
}

query listApplications($input: ListCommonInput!) {
    Application{
        listApplicationMetadata(input: $input) {
            page
            pageSize
            totalCount
            hasNextPage
            nodes {
                ... on ApplicationMetadata {
                    name
                    namespace
                    id
                    labels
                    annotations
                    displayName
                    description
                    icon
                    creator
                    creationTimestamp
                    updateTimestamp
                    isPublic
                    isRecommended
                    status
                    category
                    notReadyReasonCode
                }
            }
        }
    }
}
