# create
mutation createDatasource($input: CreateDatasourceInput!) {
  Datasource {
    createDatasource(input: $input) {
        id
        name
        namespace
        creator
        displayName
        description
        endpoint {
          url
          authSecret {
            kind
            name
          }
          insecure
        }
        oss {
          bucket
          object
        }
        creationTimestamp
        updateTimestamp
        status
        message
    }
  }
}

# update
mutation updateDatasource($input: UpdateDatasourceInput) {
  Datasource {
    updateDatasource(input: $input) {
        id
        name
        namespace
        creator
        displayName
        description
        endpoint {
          url
          authSecret {
            kind
            name
          }
          insecure
        }
        oss {
          bucket
          object
        }
        creationTimestamp
        updateTimestamp
        status
        message
    }
  }
}

# delete
mutation deleteDatasources($input: DeleteCommonInput!) {
  Datasource {
    deleteDatasources(input: $input)
  }
}

# list datasources
query listDatasources($input: ListCommonInput!) {
  Datasource {
    listDatasources(input: $input) {
    totalCount
    hasNextPage
    nodes {
      __typename
      ... on Datasource {
        id
        name
        namespace
        creator
        displayName
        description
        endpoint {
          url
          authSecret {
            kind
            name
          }
          insecure
        }
        oss {
          bucket
          object
        }
        creationTimestamp
        updateTimestamp
        status
        message
      }
      }
    }
  }
}

# get datasource
query getDatasource($name: String!, $namespace: String!) {
  Datasource {
    getDatasource(name: $name, namespace: $namespace) {
        id
        name
        namespace
        creator
        displayName
        description
        endpoint {
          url
          authSecret {
            kind
            name
          }
          insecure
        }
        oss {
          bucket
          object
        }
        creationTimestamp
        updateTimestamp
        status
message
    }
  }
}


# create
query checkDatasource($input: CreateDatasourceInput!) {
  Datasource {
    checkDatasource(input: $input) {
        name
        namespace
        status
message
    }
  }
}