query getGPT($name: String!){
    GPT{
        getGPT(name: $name) {
            name
            displayName
            description
            hot
            creator
            isRecommended
            category
            icon
            prologue
            showRespInfo
            showRetrievalInfo
            showNextGuide
            enableUploadFile
            notReadyReasonCode
        }
    }
}

query listGPTs($input: ListGPTInput!) {
    GPT{
        listGPT(input: $input) {
            page
            pageSize
            totalCount
            hasNextPage
            nodes {
                ... on GPT {
                    name
                    displayName
                    description
                    hot
                    creator
                    isRecommended
                    category
                    icon
                    prologue
                    showRespInfo
                    showRetrievalInfo
                    showNextGuide
                    enableUploadFile
                    notReadyReasonCode
                }
            }
        }
    }
}

query listGPTCategory() {
    GPT {
        listGPTCategory {
            id
            name
            nameEn
        }
    }
}