mutation createKnowledgeBaseApplication($input:CreateKnowledgeBaseApplicationInput!){
    KnowledgeBaseApplication{
        createKnowledgeBaseApplication(input: $input) {
            name
            namespace
            labels
            annotations
            displayName
            description
            icon
            isPublic
            knowledgebaseName
            llmName
            systemMessage
            userMessage
        }
    }
}

mutation updateKnowledgeBaseApplication($input: UpdateKnowledgeBaseApplicationInput!){
    KnowledgeBaseApplication{
        updateKnowledgeBaseApplication(input: $input) {
            name
            namespace
            labels
            annotations
            displayName
            description
            icon
            isPublic
            knowledgebaseName
            llmName
            systemMessage
            userMessage
        }
    }
}

mutation deleteKnowledgeBaseApplication($input: DeleteCommonInput!){
    KnowledgeBaseApplication{
        deleteKnowledgeBaseApplication(input: $input)
    }
}

query getKnowledgeBaseApplication($name: String!, $namespace: String!){
    KnowledgeBaseApplication{
        getKnowledgeBaseApplication(name: $name, namespace: $namespace) {
            name
            namespace
            labels
            annotations
            displayName
            description
            icon
            isPublic
            knowledgebaseName
            llmName
            systemMessage
            userMessage
        }
    }
}

query listKnowledgeBaseApplications($input: ListCommonInput!) {
    KnowledgeBaseApplication{
        listKnowledgeBaseApplications(input: $input) {
            page
            pageSize
            totalCount
            hasNextPage
            nodes {
                ... on KnowledgeBaseApplication {
                    name
                    namespace
                    labels
                    annotations
                    displayName
                    description
                    icon
                    isPublic
                    knowledgebaseName
                    llmName
                    systemMessage
                    userMessage
                }
            }
        }
    }
}
