# list
query listKnowledgeBases($input: ListKnowledgeBaseInput!){
  KnowledgeBase {
    listKnowledgeBases(input: $input) {
      totalCount
      hasNextPage
      nodes {
        ... on KnowledgeBase {
          id
          creationTimestamp
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          chunkSize
          chunkOverlap
          batchSize
          status
          reason
          message
          updateTimestamp
          embedder {
            kind
            name
            namespace
            displayName
          }
          embedderType
          vectorStore{
            kind
            name
          }
          fileGroupDetails {
            source{
              kind
              name
            }
            filedetails{
                path
                phase
                fileType
                count
                size
                updateTimestamp
                timeCost
            }
          }
        }
      }
    }
  }
}

# get
query getKnowledgeBase($name: String!, $namespace: String!) {
  KnowledgeBase {
    getKnowledgeBase(name: $name, namespace: $namespace){
          id
          creationTimestamp
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          chunkSize
          chunkOverlap
          batchSize
          status
          reason
          message
          updateTimestamp
          embedder {
            kind
            name
            namespace
            displayName
          }
          embedderType
          vectorStore{
            kind
            name
          }
          fileGroupDetails {
            source{
              kind
              name
            }
            filedetails{
                path
                phase
                fileType
                count
                size
                updateTimestamp
                timeCost
            }
          }
    }
  }
}

# create
mutation createKnowledgeBase($input: CreateKnowledgeBaseInput!) {
  KnowledgeBase {
    createKnowledgeBase(input: $input) {
          id
          creationTimestamp
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          chunkSize
          chunkOverlap
          batchSize
          status
          reason
          message
          updateTimestamp
          embedder {
            kind
            name
            namespace
            displayName
          }
          embedderType
          vectorStore{
            kind
            name
          }
          fileGroupDetails {
            source{
              kind
              name
            }
            filedetails{
                path
                phase
                fileType
                count
                size
                updateTimestamp
                timeCost
            }
          }
    }
  }
}

# update
mutation updateKnowledgeBase($input: UpdateKnowledgeBaseInput) {
  KnowledgeBase {
    updateKnowledgeBase(input: $input){
          id
          creationTimestamp
          name
          namespace
          labels
          annotations
          creator
          displayName
          description
          chunkSize
          chunkOverlap
          batchSize
          status
          reason
          message
          updateTimestamp
          embedder {
            kind
            name
            namespace
            displayName
          }
          embedderType
          vectorStore{
            kind
            name
          }
          fileGroupDetails {
            source{
              kind
              name
            }
            filedetails{
                path
                phase
                fileType
                count
                size
                updateTimestamp
                timeCost
            }
          }
    }
  }
}

# delete
mutation deleteKnowledgeBase($input: DeleteCommonInput) {
  KnowledgeBase {
    deleteKnowledgeBase(input: $input)
  }
}
