mutation createModelService($input: CreateModelServiceInput!) {
    ModelService {
        createModelService(input: $input) {
            id
            name
            namespace
            labels
            annotations
            creator
            displayName
            description
            types
            apiType
            creationTimestamp
            updateTimestamp
            llmResource {
                name
                namespace
                labels
                annotations
                displayName
                description
                baseUrl
                models
                provider
                type
                updateTimestamp
                status
                message
            }
            embedderResource {
                name
                namespace
                labels
                annotations
                displayName
                description
                type
                baseUrl
                models
                provider
                updateTimestamp
                status
                message
            }
            resource {
                cpu
                nvidiaGPU
                memory
            }
        }
    }
}

mutation updateModelService($input: UpdateModelServiceInput) {
    ModelService {
        updateModelService(input: $input){
            id
            name
            namespace
            labels
            annotations
            creator
            displayName
            description
            types
            apiType
            creationTimestamp
            updateTimestamp
            llmResource {
                name
                namespace
                labels
                annotations
                displayName
                description
                baseUrl
                models
                provider
                type
                updateTimestamp
                status
                message
            }
            embedderResource {
                name
                namespace
                labels
                annotations
                displayName
                description
                type
                baseUrl
                models
                provider
                updateTimestamp
                status
                message
            }
            resource {
                cpu
                nvidiaGPU
                memory
            }
        }
    }
}

mutation deleteModelServices($input: DeleteCommonInput) {
    ModelService {
        deleteModelService(input: $input)
    }
}

query getModelService($name: String!, $namespace: String!, $apiType: String!) {
    ModelService {
        getModelService(name: $name, namespace: $namespace, apiType: $apiType) {
            id
            name
            namespace
            labels
            annotations
            creator
            displayName
            description
            types
            apiType
            creationTimestamp
            updateTimestamp 
            llmResource {
                name
                namespace
                labels
                annotations
                displayName
                description
                baseUrl
                models
                provider
                type
                updateTimestamp
                status
                message
            }
            embedderResource{
                name
                namespace
                labels
                annotations
                displayName
                description
                baseUrl
                models
                provider
                type
                updateTimestamp
                status
                message
            }
            resource {
                cpu
                memory
                nvidiaGPU
            }
        }
    }
}

query listModelServices($input: ListModelService) {
    ModelService {
        listModelServices(input: $input) {
            totalCount
            hasNextPage
            nodes {
                __typename
                ... on ModelService {
                    id
                    name
                    namespace
                    labels
                    annotations
                    creator
                    displayName
                    description
                    types
                    apiType
                    creationTimestamp
                    updateTimestamp 
                    llmResource {
                        name
                        namespace
                        labels
                        annotations
                        displayName
                        description
                        baseUrl
                        models
                        provider
                        type
                        updateTimestamp
                        status
                        message
                    }
                    embedderResource{
                        name
                        namespace
                        labels
                        annotations
                        displayName
                        description
                        baseUrl
                        models
                        provider
                        type
                        updateTimestamp
                        status
                        message
                    }
                    resource {
                        cpu
                        memory
                        nvidiaGPU
                    }
                }
            }
        }
    }
}

query checkModelService($input: CreateModelServiceInput!) {
    ModelService {
        checkModelService(input: $input) {
            name
            namespace
            apiType
            description
        }
    }
}