mutation createModelService($input: CreateModelServiceInput!) {
    ModelService {
        createModelService(input: $input) {
            id
            name
            namespace
            labels
            annotations
            creator
            displayName
            description
            providerType
            types
            apiType
            creationTimestamp
            updateTimestamp
            status
            message
            baseUrl
        }
    }
}

mutation updateModelService($input: UpdateModelServiceInput) {
    ModelService {
        updateModelService(input: $input){
            id
            name
            namespace
            labels
            annotations
            creator
            displayName
            description
            providerType
            types
            apiType
            creationTimestamp
            updateTimestamp
            status
            message
            baseUrl
        }
    }
}

mutation deleteModelServices($input: DeleteCommonInput) {
    ModelService {
        deleteModelService(input: $input)
    }
}

query getModelService($name: String!, $namespace: String!) {
    ModelService {
        getModelService(name: $name, namespace: $namespace) {
            id
            name
            namespace
            labels
            annotations
            creator
            displayName
            description
            providerType
            types
            apiType
            creationTimestamp
            updateTimestamp
            status
            message
            baseUrl
        }
    }
}

query listModelServices($input: ListModelServiceInput) {
    ModelService {
        listModelServices(input: $input) {
            totalCount
            hasNextPage
            nodes {
                __typename
                ... on ModelService {
                    id
                    name
                    namespace
                    labels
                    annotations
                    creator
                    displayName
                    description
                    providerType
                    types
                    apiType
                    creationTimestamp
                    updateTimestamp
                    status
                    message
                    baseUrl
                }
            }
        }
    }
}

query checkModelService($input: CreateModelServiceInput!) {
    ModelService {
        checkModelService(input: $input) {
            name
            namespace
            apiType
            description
        }
    }
}