//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 KubeAGI.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	basev1alpha1 "github.com/kubeagi/arcadia/api/base/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonRetrieverConfig) DeepCopyInto(out *CommonRetrieverConfig) {
	*out = *in
	if in.ScoreThreshold != nil {
		in, out := &in.ScoreThreshold, &out.ScoreThreshold
		*out = new(float32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonRetrieverConfig.
func (in *CommonRetrieverConfig) DeepCopy() *CommonRetrieverConfig {
	if in == nil {
		return nil
	}
	out := new(CommonRetrieverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseRetriever) DeepCopyInto(out *KnowledgeBaseRetriever) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseRetriever.
func (in *KnowledgeBaseRetriever) DeepCopy() *KnowledgeBaseRetriever {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseRetriever)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnowledgeBaseRetriever) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseRetrieverList) DeepCopyInto(out *KnowledgeBaseRetrieverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KnowledgeBaseRetriever, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseRetrieverList.
func (in *KnowledgeBaseRetrieverList) DeepCopy() *KnowledgeBaseRetrieverList {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseRetrieverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnowledgeBaseRetrieverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseRetrieverSpec) DeepCopyInto(out *KnowledgeBaseRetrieverSpec) {
	*out = *in
	out.CommonSpec = in.CommonSpec
	in.CommonRetrieverConfig.DeepCopyInto(&out.CommonRetrieverConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseRetrieverSpec.
func (in *KnowledgeBaseRetrieverSpec) DeepCopy() *KnowledgeBaseRetrieverSpec {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseRetrieverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseRetrieverStatus) DeepCopyInto(out *KnowledgeBaseRetrieverStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseRetrieverStatus.
func (in *KnowledgeBaseRetrieverStatus) DeepCopy() *KnowledgeBaseRetrieverStatus {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseRetrieverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiQueryRetriever) DeepCopyInto(out *MultiQueryRetriever) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiQueryRetriever.
func (in *MultiQueryRetriever) DeepCopy() *MultiQueryRetriever {
	if in == nil {
		return nil
	}
	out := new(MultiQueryRetriever)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiQueryRetriever) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiQueryRetrieverList) DeepCopyInto(out *MultiQueryRetrieverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultiQueryRetriever, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiQueryRetrieverList.
func (in *MultiQueryRetrieverList) DeepCopy() *MultiQueryRetrieverList {
	if in == nil {
		return nil
	}
	out := new(MultiQueryRetrieverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiQueryRetrieverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiQueryRetrieverSpec) DeepCopyInto(out *MultiQueryRetrieverSpec) {
	*out = *in
	out.CommonSpec = in.CommonSpec
	in.CommonRetrieverConfig.DeepCopyInto(&out.CommonRetrieverConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiQueryRetrieverSpec.
func (in *MultiQueryRetrieverSpec) DeepCopy() *MultiQueryRetrieverSpec {
	if in == nil {
		return nil
	}
	out := new(MultiQueryRetrieverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiQueryRetrieverStatus) DeepCopyInto(out *MultiQueryRetrieverStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiQueryRetrieverStatus.
func (in *MultiQueryRetrieverStatus) DeepCopy() *MultiQueryRetrieverStatus {
	if in == nil {
		return nil
	}
	out := new(MultiQueryRetrieverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RerankRetriever) DeepCopyInto(out *RerankRetriever) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RerankRetriever.
func (in *RerankRetriever) DeepCopy() *RerankRetriever {
	if in == nil {
		return nil
	}
	out := new(RerankRetriever)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RerankRetriever) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RerankRetrieverList) DeepCopyInto(out *RerankRetrieverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RerankRetriever, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RerankRetrieverList.
func (in *RerankRetrieverList) DeepCopy() *RerankRetrieverList {
	if in == nil {
		return nil
	}
	out := new(RerankRetrieverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RerankRetrieverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RerankRetrieverSpec) DeepCopyInto(out *RerankRetrieverSpec) {
	*out = *in
	out.CommonSpec = in.CommonSpec
	in.CommonRetrieverConfig.DeepCopyInto(&out.CommonRetrieverConfig)
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(basev1alpha1.TypedObjectReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RerankRetrieverSpec.
func (in *RerankRetrieverSpec) DeepCopy() *RerankRetrieverSpec {
	if in == nil {
		return nil
	}
	out := new(RerankRetrieverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RerankRetrieverStatus) DeepCopyInto(out *RerankRetrieverStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RerankRetrieverStatus.
func (in *RerankRetrieverStatus) DeepCopy() *RerankRetrieverStatus {
	if in == nil {
		return nil
	}
	out := new(RerankRetrieverStatus)
	in.DeepCopyInto(out)
	return out
}
